# Define networks and services here
#
# If a container service needs access to a Stoobly defined service, 
# then the container service needs to add the service name to the 'networks' property
# e.g. If we have defined a 'upstream' service, then the following should be added
# networks:
#   - upstream
# 
# Container services that are intended to be run as part of a workflow need to have the workflow name added to the 'profiles' property
# e.g. If we want to run a service as part of the 'record' workflow, then the following should be added
# profiles:
#   - record
networks: {}
services: {}