x-base: &base
  env_file:
    - .env
  networks:
    - app.ingress
  profiles:
    - ${WORKFLOW_NAME}

# Define custom services here
#
# 1. Uncomment the following
# 2. Replace <URL> with the URL to test
# 3. Modify as needed
#
# To learn more, see https://docs.stoobly.com/core-concepts/scaffold

#services:
#  entrypoint.curl:
#    <<: *base
#    depends_on:
#      entrypoint.configure:
#        condition: service_completed_successfully
#    image: curlimages/curl
#    command: ["curl", "-x", "http://$APP_PROXY_HOSTNAME:$APP_PROXY_PORT" , "-k", "<URL>"]