services:
  stoobly_ui.service:
    command: --ui-port 4200
    extends:
      file: ../.docker-compose.base.yml
      service: stoobly_ui.base
    image: stoobly.${USER_ID}
    ports:
      - '4200:4200'
    profiles:
      - record

